Add getBoard(), (immutablly) to Board.java
drtnf/threeChess pull request #19
Opened 2020-10-17 14:12 UTC by CyanPhotonics

This adds a helper method to Board.java to allow you to access the game board (though not change it) for use in things such as caching based on the board state.

2020-10-19 04:10 UTC, drtnf requested changes
This seems ok, but the method name should be getPieceMap, or something like that. getBoard inside class Board that does not return a Board is wierd.

2020-10-19 04:27 UTC, CyanPhotonics commented
I've corrected the name, and added a note to it's usage.

2020-10-20 01:45 UTC, drtnf requested changes
You should take your gitignore out of the pull request. Also, your note makes me wonder about the utility of this change. Might be less confusing just to return a clone of the board map?

2020-10-20 04:39 UTC, CyanPhotonics commented
While I would prefer and API that allows minimizing heap allocation, you are right that it is a little confusing with Javas limited ability to express ownership, and in my use it needs a copy anyway.

2020-10-20 06:11 UTC, drtnf approved these changes
Thanks.

2020-10-20 06:11 UTC, merged